id: P010632
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN4350
  title: ཐ་སྙད་རྒྱུན་བཀོལ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    b8a8f4672f4547fab98217e482b62a4e:
      image_group_id: I3CN4558
      title: ''
      volume_number: 1
      total_pages: 38
      base_file: v001.txt
